### ISSUE TITLE
discarded datum and projected points not finite

### ISSUE THREAD

**Issue by lime-n** [rspatial/raster#167]
When I read my .tif file into r using the raster function, I get these warning messages:
```
Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps unknown in CRS definition: +proj=sinu +lon_0=0 +x_0=0 +y_0=0 +R=6371007.181 +units=m +no_defs
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum unknown in CRS definition
```

It does not seem to impact the coding however, any reasoning as to why this happens?

**Comment by rhijmans** [comment]
The file provides no datum (or a datum that is not understood, perhaps because the proj.4. notation was used with a datum other than WGS94/NAD83. As long as you do not transform your data ("project"), this should not affect anything. This is probably caused by recent changes to GDAL. See https://cran.r-project.org/web/packages/rgdal/vignettes/CRS_projections_transformations.html and https://www.r-spatial.org/r/2020/03/17/wkt.html.
