### ISSUE TITLE
Get band number of maximum value per pixel for multiband raster in R?

### ISSUE THREAD

**Issue by spariyar** [rspatial/raster#236]
I have a multiband raster stack and I want to find the band number of the maximum value for each pixel. For this, I have used the following code:
#Set working directory
setwd("E:/Red Panda/TIF")
library(raster)

#Get the names of all the files with extension ".tif" of the folder
files <- list.files("E:/Red Panda/TIF/", pattern='tif$', full.names=TRUE )
files
Raster_stack <- stack(files)
Raster_stack
names(Raster_stack)
plot(Raster_stack)

#Identify pixel-wise band with max value
pixelMaxBand.ras <- whiches.max(Raster_stack)

But I found this type of error:
Error in .local(x, ...) :
you can use only use this function for an object with less than 10 layers

Generally, I have >10 raster layers for different land use and land cover but this “whiches.max” function works for layers less than 10. Can you please suggest me the appropriate code that can work for rasters >10? Thank you.

**Comment by ailich** [comment]
Based on the function help it says "(whiches.*). An integer in which each digit represents a layer. For example, 35 means 'layers 3 and 5' so the that's why it can't work with more than 10. For example  "12" could represent either 1 and 2 or 12. If you're not worried about ties in values among your layers, you could use `which.max`.

**Comment by rhijmans** [comment]
I think this question was answered [here](https://gis.stackexchange.com/questions/418673/making-new-categorical-raster-selected-from-stack-having-maximum-values-for-each/418812#418812)
