### ISSUE TITLE
writeRaster() does not follow "filetype= " argument with ".grd" file extension.

### ISSUE THREAD

**Issue by mmrgeodk** [rspatial/raster#288]
writeRaster() does not follow "filetype= " argument when the filename has a ".grd" file extension. 

The command writeRaster(any_raster, filename = "any_raster.grd", filetype = "GS7BG") results in a grd-file in raster-format and not in "GS7BG (Golden Software Surfer Binary)" format. The same for other filetypes with .grd file extensions.

**Comment by kadyb** [comment]
Sorry, I wrote too quickly and `{raster}` supports this format too: https://rspatial.github.io/raster/reference/writeFormats.html

**Comment by rhijmans** [comment]
Thanks, that was a bug in raster::writeRaster. I now get:

```
library(raster)
r <- raster(nrows = 5, ncols = 5, vals = 1:25)
writeRaster(r, "surf.grd", format = "GS7BG", overwrite = TRUE)
terra::describe("surf.grd")[1]
#[1] "Driver: GS7BG/Golden Software 7 Binary Grid (.grd)"
```

Note that although you can call `terra::writeRaster` with a `RasterLayer` object, what will be used is `raster::writeRaster` because the dispatch of the generic `writeRaster` depends on the class of `x` (the first argument).  `package::method` can make a difference when another package (probably not importing terra or raster) overwrites `writeRaster`, but that is not the case here.

Also note that while `terra::writeRaster` has the argument `filetype`, `raster::writeRaster` has the equivalent argument `format`; so you must use `format` here.

**Comment by mmrgeodk** [comment]
Well, that still does not work correctly:


```
library(raster)

r = raster(nrows = 5, ncols = 5, vals = 1:25)
raster::writeRaster(r, "test.grd", format = "GS7BG", overwrite = TRUE)

library(terra)
describe("test.grd")[1]
>[1] "Driver: RRASTER/R Raster"
```
