### ISSUE TITLE
reclassify: keep layer names?

### ISSUE THREAD

**Issue by MatthieuStigler** [rspatial/raster#42]
Hi Robert

It would be great if `reclassify` could keep original layer names? For now they are lost. 

Thanks!!

``` r
library(raster)
#> Loading required package: sp
r <- raster(ncols=36, nrows=18)
r[] <- runif(ncell(r)) 
r$new <- runif(ncell(r)) 
rclmat <- matrix(c(0, 0.25, 1,  0.25, 0.5, 2,  0.5, 1, 3), ncol=3, byrow=TRUE)
r2 <- reclassify(r, rclmat)
names(r)
#> [1] "layer" "new"
names(r2)
#> [1] "layer.1" "layer.2"
```

**Comment by rhijmans** [comment]
That is by design: the names are maintained with, for example, "crop" as the cell values do not change. But after "reclassify" you are not really dealing with the same variable anymore. I am not saying the design is a good one --- it is more practical to keep the names, and there is not much of a downside, if any.  I think I will change it as you suggest.

**Comment by MatthieuStigler** [comment]
oh nice, I see you already did it in https://github.com/rspatial/raster/commit/d234b7f173a2da7b9df22118a3b6546eaf794a93

thanks!!
